language: minimal

services:
  - docker

script:
  - docker-compose run tests
  - docker-compose run doc

deploy:
  provider: pages
  local-dir: docs/norm-docs.mkdocs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
