os: linux
language: shell

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose run tests
  - docker-compose run book
  - docker-compose run docs

deploy:
  provider: pages
  local_dir: docs
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: develop

