version: '3'
services:
  db:
    image: postgres
  test:
    image: nimlang/nim:latest
    working_dir: /usr/src/app
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: bash -c "nimble install -y && nimble test"
