version: '3'

foo

services:

  postgres_1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  postgres_2:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  tests:
    build: .
    image: norm
    depends_on:
      - postgres_1
      - postgres_2
    volumes:
      - .:/usr/src/app
    command: nimble test

  test:
    build: .
    image: norm
    depends_on:
      - postgres_1
      - postgres_2
    volumes:
      - .:/usr/src/app
    entrypoint: nim c -r

  docs:
    build: .
    image: norm
    volumes:
      - .:/usr/src/app
    command: nimble docs
