version: '3'
services:
  postgres_1:
    image: postgres:11
  postgres_2:
    image: postgres:11
  tests:
    build: .
    image: norm
    depends_on:
      - postgres_1
      - postgres_2
    volumes:
      - .:/usr/src/app
    command: nimble test
  test:
    build: .
    image: norm
    depends_on:
      - postgres_1
      - postgres_2
    volumes:
      - .:/usr/src/app
    entrypoint: nim c -r
  docs:
    build: .
    image: norm
    volumes:
      - .:/usr/src/app
    command:
      - sh
      - -c
      - |
        nim doc --project --index:on \
          --git.url:https://github.com/moigagoo/norm/ \
          --git.commit:develop \
          /usr/src/app/src/norm.nim &&
        nim buildIndex -o:/usr/src/app/src/htmldocs/theindex.html \
          /usr/src/app/src/htmldocs
