version: '3'
services:
  postgres:
    image: postgres:11
  tests:
    build: .
    image: norm
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: nimble test
  test:
    build: .
    image: norm
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    entrypoint: nim c -r
  docs:
    image: nimlang/nim:0.20.0
    volumes:
      - .:/usr/src/app
    command: "nim doc --project /usr/src/app/src/norm.nim"
