version: '3'
services:
  db:
    image: postgres
  tests:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: nimble test
  testpostgres:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: nim c -r tests/testpostgres.nim
  docs:
    image: nimlang/nim
    volumes:
      - .:/usr/src/app
    command: "nim doc --project /usr/src/app/src/norm.nim"
