version: '3'
services:
  db:
    image: postgres
  test:
    build: .
    image: norm
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: nimble test
  testpostgres:
      build: .
      image: norm
      depends_on:
        - db
      volumes:
        - .:/usr/src/app
      command: nim c -r tests/testpostgres.nim
