name: Norm tests, book, and docs
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tests
        run: docker-compose run tests

  Book & Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Book
        run: docker-compose run book

      - name: Docs
        run: docker-compose run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

